apiVersion: bolt/v1
kind: Service
metadata:
  name: aws-comprehensive-example
  owner: yourname
  tags:
    environment: "local"
    project: "bolt-aws-demo"
    cost-center: "engineering"
    team: "platform"

providers:
  - name: aws_local
    type: aws
    spec:
      region: us-east-1
      environment: local

spec:
  key_pair:
    name: "aws-key"
    public_key_file: "~/.ssh/id_rsa.pub"
    use_existing: true
  
  infrastructure:
    networks:
      - name: vpc-main
        provider: aws_local
        cidr: 10.10.0.0/16
        subnets:
          - name: subnet-public-1a
            zone: us-east-1a
            cidr: 10.10.1.0/24
          - name: subnet-public-1b
            zone: us-east-1b
            cidr: 10.10.2.0/24
          - name: subnet-private-1a
            zone: us-east-1a
            cidr: 10.10.3.0/24
          - name: subnet-private-1b
            zone: us-east-1b
            cidr: 10.10.4.0/24
    
    security_groups:
      - name: web-sg
        provider: aws_local
        vpc: vpc-main
        rules:
          - type: ingress
            protocol: tcp
            from_port: 22
            to_port: 22
            cidr_blocks: ["0.0.0.0/0"]
          - type: ingress
            protocol: tcp
            from_port: 80
            to_port: 80
            cidr_blocks: ["0.0.0.0/0"]
          - type: ingress
            protocol: tcp
            from_port: 443
            to_port: 443
            cidr_blocks: ["0.0.0.0/0"]
          - type: egress
            protocol: -1
            from_port: 0
            to_port: 0
            cidr_blocks: ["0.0.0.0/0"]
      
      - name: app-sg
        provider: aws_local
        vpc: vpc-main
        rules:
          - type: ingress
            protocol: tcp
            from_port: 22
            to_port: 22
            source_vpc: vpc-main
          - type: ingress
            protocol: tcp
            from_port: 8080
            to_port: 8080
            source_vpc: vpc-main
          - type: egress
            protocol: -1
            from_port: 0
            to_port: 0
            cidr_blocks: ["0.0.0.0/0"]
    
    computes:
      - name: web-server-1
        type: ec2
        provider: aws_local
        vpc: vpc-main
        subnet: subnet-public-1a
        security_group: web-sg
        spec:
          instance_type: t3.micro
          root_disk_size_gb: 20
      
      - name: web-server-2
        type: ec2
        provider: aws_local
        vpc: vpc-main
        subnet: subnet-public-1b
        security_group: web-sg
        spec:
          instance_type: t3.micro
          root_disk_size_gb: 20
      
      - name: app-server-1
        type: ec2
        provider: aws_local
        vpc: vpc-main
        subnet: subnet-private-1a
        security_group: app-sg
        spec:
          instance_type: t3.small
          root_disk_size_gb: 40
      
      - name: app-server-2
        type: ec2
        provider: aws_local
        vpc: vpc-main
        subnet: subnet-private-1b
        security_group: app-sg
        spec:
          instance_type: t3.small
          root_disk_size_gb: 40