apiVersion: bolt/v1
kind: Service
metadata:
  name: example-azure-service
  owner: yourname
  tags:
    environment: "local"  # Ganti ke "production" untuk Azure asli
    project: "bolt-demo"
providers:
  - name: azurerm_local
    type: azurerm
    spec:
      region: eastus
      environment: local  # Ganti ke "production" untuk Azure asli
      # Untuk production, login dengan: az login
      # Atau gunakan service principal: az login --service-principal

spec:
  key_pair:
    name: "azure-key"
    public_key_file: "~/.ssh/id_rsa.pub"
    use_existing: true
  infrastructure:
    # Gunakan key pair yang sudah ada (Azure: SSH public key sudah di-upload manual)
    # Untuk production, upload SSH public key ke Azure: az sshkey create
    networks:
      - name: vnet-main
        provider: azurerm_local
        cidr: 10.10.0.0/16
        subnets:
          - name: subnet-public
            zone: eastus
            cidr: 10.10.1.0/24
    security_groups:
      - name: nsg-web
        provider: azurerm_local
        vpc: vnet-main
        rules:
          - type: ingress
            protocol: tcp
            from_port: 22
            to_port: 22
            cidr_blocks: ["0.0.0.0/0"]
    computes:
      - name: web-vm
        type: azurerm_linux_virtual_machine
        provider: azurerm_local
        vpc: vnet-main
        subnet: subnet-public
        security_group: nsg-web
        spec:
          size: Standard_B1s
          root_disk_size_gb: 20 